# INMERSION DE DATOS CON PYTHON

In [85]:
# prompt: importa los siguientes m√≥dulos con sus respectivos alias: pandas, matplotlib, seaborn, drive de google colab, warnings

# # INMERSION DE DATOS CON PYTHON
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import drive
import warnings

from google.colab import drive
drive.mount("/content/drive")
import warnings
warnings.filterwarnings("ignore")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [86]:
pd.set_option("display.max_columns",None)
global df_banco, resultados

In [87]:
df_banco = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/german_credit.csv")
df_banco.head()

,default,account_check_status,duration_in_month,credit_history,purpose,credit_amount,savings,present_emp_since,installment_as_income_perc,personal_status_sex,other_debtors,present_res_since,property,age,other_installment_plans,housing,credits_this_bank,job,people_under_maintenance,telephone,foreign_worker
0,0,< 0 DM,6,critical account/ other credits existing (not ...,domestic appliances,1169,unknown/ no savings account,.. >= 7 years,4,male : single,none,4,real estate,67,none,own,2,skilled employee / official,1,"yes, registered under the customers name",yes
1,1,0 <= ... < 200 DM,48,existing credits paid back duly till now,domestic appliances,5951,... < 100 DM,1 <= ... < 4 years,2,female : divorced/separated/married,none,2,real estate,22,none,own,1,skilled employee / official,1,none,yes
2,0,no checking account,12,critical account/ other credits existing (not ...,(vacation - does not exist?),2096,... < 100 DM,4 <= ... < 7 years,2,male : single,none,3,real estate,49,none,own,1,unskilled - resident,2,none,yes
3,0,< 0 DM,42,existing credits paid back duly till now,radio/television,7882,... < 100 DM,4 <= ... < 7 years,2,male : single,guarantor,4,if not A121 : building society savings agreeme...,45,none,for free,1,skilled employee / official,2,none,yes
4,1,< 0 DM,24,delay in paying off in the past,car (new),4870,... < 100 DM,1 <= ... < 4 years,3,male : single,none,4,unknown / no property,53,none,for free,2,skilled employee / official,2,none,yes

In [88]:
df_banco.shape

(1000, 21)

In [89]:
df_banco.columns

Index(['default', 'account_check_status', 'duration_in_month',
       'credit_history', 'purpose', 'credit_amount', 'savings',
       'present_emp_since', 'installment_as_income_perc',
       'personal_status_sex', 'other_debtors', 'present_res_since', 'property',
       'age', 'other_installment_plans', 'housing', 'credits_this_bank', 'job',
       'people_under_maintenance', 'telephone', 'foreign_worker'],
      dtype='object')

In [90]:
df_banco.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   default                     1000 non-null   int64
 1   account_check_status        1000 non-null   object
 2   duration_in_month           1000 non-null   int64
 3   credit_history              1000 non-null   object
 4   purpose                     1000 non-null   object
 5   credit_amount               1000 non-null   int64
 6   savings                     1000 non-null   object
 7   present_emp_since           1000 non-null   object
 8   installment_as_income_perc  1000 non-null   int64
 9   personal_status_sex         1000 non-null   object
 10  other_debtors               1000 non-null   object
 11  present_res_since           1000 non-null   int64
 12  property                    1000 non-null   object
 13  age                         1000 non-null   int64
 14  other_installment_plans     1000 non-null   object
 15  housing                     1000 non-null   object
 16  credits_this_bank           1000 non-null   int64
 17  job                         1000 non-null   object
 18  people_under_maintenance    1000 non-null   int64
 19  telephone                   1000 non-null   object
 20  foreign_worker              1000 non-null   object
dtypes: int64(8), object(13)
memory usage: 164.2+ KB

In [91]:
df_banco.account_check_status.value_counts().index

Index(['no checking account', '< 0 DM', '0 <= ... < 200 DM',
       '>= 200 DM / salary assignments for at least 1 year'],
      dtype='object', name='account_check_status')

In [92]:
columnas = list(df_banco.select_dtypes(include=['object']).columns)
for columnas in columnas:
  print(f'El nombre de la columna: {columnas}')
  print(list(df_banco[f'{columnas}'].value_counts().index))
  print('\n')

El nombre de la columna: account_check_status
['no checking account', '< 0 DM', '0 <= ... < 200 DM', '>= 200 DM / salary assignments for at least 1 year']


El nombre de la columna: credit_history
['existing credits paid back duly till now', 'critical account/ other credits existing (not at this bank)', 'delay in paying off in the past', 'all credits at this bank paid back duly', 'no credits taken/ all credits paid back duly']


El nombre de la columna: purpose
['domestic appliances', 'car (new)', 'radio/television', 'car (used)', 'business', '(vacation - does not exist?)', 'education', 'repairs', 'furniture/equipment', 'retraining']


El nombre de la columna: savings
['... < 100 DM', 'unknown/ no savings account', '100 <= ... < 500 DM', '500 <= ... < 1000 DM ', '.. >= 1000 DM ']


El nombre de la columna: present_emp_since
['1 <= ... < 4 years', '.. >= 7 years', '4 <= ... < 7 years', '... < 1 year ', 'unemployed']


El nombre de la columna: personal_status_sex
['male : single', 'female : divorced/separated/married', 'male : married/widowed', 'male : divorced/separated']


El nombre de la columna: other_debtors
['none', 'guarantor', 'co-applicant']


El nombre de la columna: property
['if not A121/A122 : car or other, not in attribute 6', 'real estate', 'if not A121 : building society savings agreement/ life insurance', 'unknown / no property']


El nombre de la columna: other_installment_plans
['none', 'bank', 'stores']


El nombre de la columna: housing
['own', 'rent', 'for free']


El nombre de la columna: job
['skilled employee / official', 'unskilled - resident', 'management/ self-employed/ highly qualified employee/ officer', 'unemployed/ unskilled - non-resident']


El nombre de la columna: telephone
['none', 'yes, registered under the customers name ']


El nombre de la columna: foreign_worker
['yes', 'no']

In [93]:
# dic = {'yes':1, 'no':0}
# df_banco['foreign_worker'] = df_banco['foreign_worker'].map(dic)
# df_banco['foreign_worker']

In [94]:
def procesar_datos():
  global df_banco
  df_banco = df_banco.drop_duplicates() if df_banco.duplicated().any() else df_banco
  df_banco = df_banco.dropna() if df_banco.isnull().values.any() else df_banco

a = {'no checking account': 4,
      '>= 200 DM / salary assignments for at least 1 year': 3,
      '0 <= ... < 200 DM': 2,
      '< 0 DM': 1
  }
df_banco['account_check_status'] = df_banco['account_check_status'].map(a)

a = { 'no credits taken/ all credits paid back duly' : 1,
      'all credits at this bank paid back duly' : 2,
      'existing credits paid back duly till now' : 3,
      'delay in paying off in the past' : 4,
      'critical account/ other credits existing (not at this bank)' : 5
  }
df_banco['credit_history'] = df_banco['credit_history'].map(a)

a = {'car (new)' : 1,
      'car (used)' : 2,
      'furniture/equipment' : 3,
      'radio/television' : 4,
      'domestic appliances' : 5,
      'repairs' : 6,
      'education' : 7,
      '(vacation - does not exist?)' : 8,
      'retraining' : 9,
      'business' : 10,
      'others' : 11
  }
df_banco['purpose'] = df_banco['purpose'].map(a)

a = {'unknown/ no savings account' : 1,
      '.. >= 1000 DM ' : 2,
      '500 <= ... < 1000 DM ' : 3,
      '100 <= ... < 500 DM' : 4,
      '... < 100 DM' : 5
  }
df_banco['savings'] = df_banco['savings'].map(a)

a = {'.. >= 7 years' : 1,
      '4 <= ... < 7 years' : 2,
      '1 <= ... < 4 years' : 3,
      '... < 1 year ' : 4,
      'unemployed' : 5
  }
df_banco['present_emp_since'] = df_banco['present_emp_since'].map(a)

a = {'male : divorced/separated' : 1,
      'female : divorced/separated/married' : 2,
      'male : single' : 3,
      'male : married/widowed' : 4,
      'female : single' : 5
  }
df_banco['personal_status_sex'] = df_banco['personal_status_sex'].map(a)

a = {'none' : 1,
      'co-applicant' : 2,
      'guarantor' : 3
  }
df_banco['other_debtors'] = df_banco['other_debtors'].map(a)

a = {'real estate' : 1,
      'if not A121 : building society savings agreement/ life insurance' : 2,
      'if not A121/A122 : car or other, not in attribute 6' : 3,
      'unknown / no property' : 4
  }
df_banco['property'] = df_banco['property'].map(a)

a = {'bank' : 1,
      'stores' : 2,
      'none' : 3
  }
df_banco['other_installment_plans'] = df_banco['other_installment_plans'].map(a)

a = {'rent' : 1,
      'own' : 2,
      'for free' : 3
  }
df_banco['housing'] = df_banco['housing'].map(a)

a = {'unemployed/ unskilled - non-resident' : 1,
      'unskilled - resident' : 2,
      'skilled employee / official' : 3,
      'management/ self-employed/ highly qualified employee/ officer' : 4
  }
df_banco['job'] = df_banco['job'].map(a)

a = {'yes, registered under the customers name ' : 1,
      'none' : 0
  }
df_banco['telephone'] = df_banco['telephone'].map(a)
a = {'yes':1, 'no':0
  }
df_banco['foreign_worker'] = df_banco['foreign_worker'].map(a)

In [95]:
procesar_datos()
df_banco.sample(5)

,default,account_check_status,duration_in_month,credit_history,purpose,credit_amount,savings,present_emp_since,installment_as_income_perc,personal_status_sex,other_debtors,present_res_since,property,age,other_installment_plans,housing,credits_this_bank,job,people_under_maintenance,telephone,foreign_worker
661,1,1,12,3,1,900,1,3,4,4,1,2,3,23,3,2,1,3,1,0,1
417,0,1,18,4,8,8471,1,3,1,2,1,2,3,23,3,1,2,3,1,1,1
375,1,1,48,2,10,7685,5,2,2,2,3,4,3,37,3,1,1,3,1,0,1
404,0,2,18,4,1,2899,1,1,4,3,1,4,3,43,3,2,1,3,2,0,1
351,1,2,9,3,4,959,5,3,1,2,1,2,3,29,3,2,1,3,1,0,0

In [96]:
variables_discretas = ['personal_status_sex','age',
                       'duration_in_month','credit_amount','default']
df_banco[variables_discretas].tail(3)

     personal_status_sex  age  duration_in_month  credit_amount  default
997                    3   38                 12            804        0
998                    3   23                 45           1845        1
999                    3   27                 45           4576        0